version: "3.8"

services:
  web:
    build: .
    container_name: tools-web
    ports:
      - "80:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - tools-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  tools-network:
    driver: bridge
