name: tools

services:
  tools:
    container_name: tools
    image: ghcr.io/lengbumo/tools:latest
    ports:
      - "8999:80"
    restart: always
    environment:
      - NODE_ENV=production
    labels:
      - "com.docker.compose.project=tools"
      - "com.docker.compose.service=tools"
